{% set name = "cmd2" %}
{% set version = "4.0.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "97956c491be8ae2c5239ba1e7658b52804f0e54b401b15cae80c6b85c9dce74f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools

  run:
    - python
    - setuptools
    - pyperclip >=1.6
    - pyreadline3  # [win]
    - wcwidth >=0.1.7
    - gnureadline  # [osx]
    - rich-argparse >=1.7.1
    - backports.strenum  # [py==310]

test:
  imports:
    - cmd2

about:
  home: https://github.com/python-cmd2/cmd2
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Extra features for standard library's cmd module
  dev_url: https://github.com/python-cmd2/cmd2
  doc_url: https://cmd2.readthedocs.io/

extra:
  recipe-maintainers:
    - anguslees
    - tschoonj
